### Raiz da aplicação
GET http://localhost:5090/

### Listagem de Produtos
GET http://localhost:5090/produto/listar

### Busca de Produtos por nome
GET http://localhost:5090/produto/buscar/Televisão

### Cadastro de Produtos
POST http://localhost:5090/produto/cadastrar
Content-Type: application/json

{
    "nome" : "Arroz",
    "descricao": "Alimento",
    "Valor": 10
}


### Deletar produtos

DELETE http://localhost:5090/produto/deletar/Arroz

### Alterar Produto

PATCH http://localhost:5090/produto/alterar/Arroz/Grão/8